"""Changing sync_metadata model

Revision ID: 3e4a79fa15d3
Revises: 696f951a3582
Create Date: 2026-03-01 18:46:33.698682

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3e4a79fa15d3"
down_revision: str | Sequence[str] | None = "696f951a3582"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
