"""outbox_add_retry_count

Revision ID: 4474e8a34eb4
Revises: a2478a380803
Create Date: 2026-03-17 21:59:44.543165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4474e8a34eb4"
down_revision: Union[str, Sequence[str], None] = "a2478a380803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox",
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###
    op.alter_column(
        "ticket",
        "idempotency_key",
        existing_type=sa.VARCHAR(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    # Add the CHECK constraint
    op.create_check_constraint("retry_count_non_negative", "outbox", "retry_count >= 0")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("retry_count_non_negative", "outbox", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox", "retry_count")
    # ### end Alembic commands ###
