"""Changing sync_metadata model

Revision ID: 696f951a3582
Revises: a1783db4b365
Create Date: 2026-03-01 18:04:00.200077

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "696f951a3582"
down_revision: str | Sequence[str] | None = "a1783db4b365"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_metadata",
        sa.Column(
            "sync_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
    )
    op.add_column("sync_metadata", sa.Column("status", sa.String(), nullable=False))
    op.add_column(
        "sync_metadata",
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column("sync_metadata", sa.Column("type", sa.String(), nullable=True))
    op.drop_column("sync_metadata", "updated_at")
    op.drop_column("sync_metadata", "value")
    op.drop_column("sync_metadata", "key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_metadata",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "sync_metadata",
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "sync_metadata",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('UTC'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sync_metadata", "type")
    op.drop_column("sync_metadata", "last_changed_at")
    op.drop_column("sync_metadata", "status")
    op.drop_column("sync_metadata", "sync_timestamp")
    # ### end Alembic commands ###
